"""Tests for the recursive joint water-balance estimator."""

from __future__ import annotations

from dataclasses import replace

import numpy as np
import pytest

from custom_components.amazing_irrigation.estimator import (
    COEFFICIENT_NAMES,
    EstimatorObservation,
    JointEstimator,
)
from custom_components.amazing_irrigation.waterbalance import (
    DRAIN_RATE_MAX,
    DRAIN_RATE_MIN,
    ETA_IRR_MAX,
    ETA_IRR_MIN,
    ETA_RAIN_MAX,
    ETA_RAIN_MIN,
    K_ET_MAX,
    K_ET_MIN,
    Climate,
    WaterBalanceParams,
    default_params,
    step,
)

RNG_SEED = 20260628


def _climates() -> list[Climate]:
    return [
        Climate(air_temp_c=18.0, air_humidity_pct=70.0, wind_ms=0.5, solar=120.0),
        Climate(air_temp_c=24.0, air_humidity_pct=55.0, wind_ms=1.6, solar=420.0),
        Climate(air_temp_c=31.0, air_humidity_pct=35.0, wind_ms=2.5, solar=690.0),
        Climate(air_temp_c=14.0, air_humidity_pct=82.0, wind_ms=0.2, solar=40.0),
    ]


def _synthetic_observations(
    true_params: WaterBalanceParams,
    *,
    count: int,
    protected_rain: bool = False,
    simultaneous: bool = False,
    noise_std: float = 0.0,
) -> list[EstimatorObservation]:
    rng = np.random.default_rng(RNG_SEED)
    climates = _climates()
    observations: list[EstimatorObservation] = []
    for index in range(count):
        if simultaneous:
            theta_start = 39.0 + (index % 23) * 1.35
            liters = 0.25 + (index % 6) * 0.18
            rain_mm = 0.12 + (index % 5) * 0.16
            dt = 1.0 + (index % 4) * 0.55
        else:
            theta_start = 24.0 + (index % 41) * 1.15
            liters = 0.0 if index % 3 == 0 else 0.20 + (index % 7) * 0.16
            rain_mm = 0.0 if index % 4 == 0 else 0.15 + (index % 5) * 0.20
            dt = 0.75 + (index % 6) * 0.45
        if index % 9 == 0:
            theta_start = true_params.field_capacity + 3.0 + (index % 5) * 1.4
            liters = 0.0
            rain_mm = 0.0 if protected_rain else rain_mm
        climate = climates[index % len(climates)]
        result = step(
            true_params,
            theta_start,
            liters=liters,
            rain_mm=rain_mm,
            climate=climate,
            dt=dt,
            protected_rain=protected_rain,
        )
        theta_end = result.theta_next
        if noise_std:
            theta_end = float(
                np.clip(theta_end + rng.normal(0.0, noise_std), 0.0, 100.0)
            )
        observations.append(
            EstimatorObservation(
                theta_start=theta_start,
                theta_end=theta_end,
                dt=dt,
                liters=liters,
                rain_mm=rain_mm,
                climate=climate,
                protected_rain=protected_rain,
            )
        )
    return observations


def _assert_coefficients_close(
    estimate: WaterBalanceParams, true_params: WaterBalanceParams
) -> None:
    assert estimate.eta_irr == pytest.approx(true_params.eta_irr, abs=0.08)
    assert estimate.eta_rain == pytest.approx(true_params.eta_rain, abs=0.08)
    assert estimate.k_et == pytest.approx(true_params.k_et, abs=0.05)
    assert estimate.drain_rate == pytest.approx(true_params.drain_rate, abs=0.03)


def test_recovers_joint_coefficients_from_synthetic_waterbalance_intervals():
    """RLS recovers known coefficients generated by the physics core."""
    true_params = WaterBalanceParams(1.85, 1.35, 0.58, 0.16, 48.0, 17.0)
    prior = replace(default_params("loam"), field_capacity=48.0, wilting_point=17.0)
    estimator = JointEstimator(
        prior,
        prior_cov=[16.0, 16.0, 2.0, 0.25],
        overrides={"field_capacity": 48.0, "wilting_point": 17.0},
    )

    estimator.fit(_synthetic_observations(true_params, count=240))

    _assert_coefficients_close(estimator.params, true_params)
    assert all(0.0 <= value <= 1.0 for value in estimator.confidence.values())


def test_protected_rain_does_not_drive_rain_efficiency():
    """Greenhouse/protected-zone rain is projected out of the rain regressor."""
    true_params = WaterBalanceParams(1.7, 2.6, 0.62, 0.12, 46.0, 16.0)
    prior = WaterBalanceParams(1.0, 0.42, 0.9, 0.05, 46.0, 16.0)
    estimator = JointEstimator(
        prior,
        prior_cov=[12.0, 12.0, 1.0, 0.16],
        overrides={"field_capacity": 46.0, "wilting_point": 16.0},
    )

    estimator.fit(
        _synthetic_observations(true_params, count=180, protected_rain=True)
    )

    assert estimator.params.eta_irr == pytest.approx(true_params.eta_irr, abs=0.10)
    assert estimator.params.k_et == pytest.approx(true_params.k_et, abs=0.06)
    assert estimator.params.drain_rate == pytest.approx(true_params.drain_rate, abs=0.04)
    assert estimator.params.eta_rain == pytest.approx(prior.eta_rain)
    assert estimator.confidence["eta_rain"] < 0.10


def test_joint_attribution_converges_with_simultaneous_water_rain_and_drying():
    """Overlapping water, rain, ET, and drainage are decomposed jointly."""
    true_params = WaterBalanceParams(1.45, 1.05, 0.72, 0.10, 50.0, 18.0)
    prior = replace(default_params("loam"), field_capacity=50.0, wilting_point=18.0)
    estimator = JointEstimator(
        prior,
        prior_cov=[20.0, 20.0, 2.0, 0.20],
        overrides={"field_capacity": 50.0, "wilting_point": 18.0},
    )

    estimator.fit(
        _synthetic_observations(true_params, count=300, simultaneous=True)
    )

    _assert_coefficients_close(estimator.params, true_params)


def test_bounded_and_stable_on_garbage_input():
    """Non-finite, absurd, and zero-variance data never escape safe bounds."""
    estimator = JointEstimator(default_params("sand"), prior_cov=1e9, forgetting=-5.0)
    bad_values = [float("nan"), float("inf"), -float("inf"), 1e100, -1e100, 50.0]

    for value in bad_values:
        estimator.update(
            theta_start=value,
            theta_end=-value if np.isfinite(value) else value,
            dt=value,
            liters=value,
            rain_mm=value,
            climate=Climate(value, value),
        )
    for _ in range(10):
        estimator.update(theta_start=42.0, theta_end=42.0, dt=0.0)

    params = estimator.params
    assert ETA_IRR_MIN <= params.eta_irr <= ETA_IRR_MAX
    assert ETA_RAIN_MIN <= params.eta_rain <= ETA_RAIN_MAX
    assert K_ET_MIN <= params.k_et <= K_ET_MAX
    assert DRAIN_RATE_MIN <= params.drain_rate <= DRAIN_RATE_MAX
    assert params.field_capacity > params.wilting_point
    assert np.all(np.isfinite(estimator.covariance))
    assert all(0.0 <= value <= 1.0 for value in estimator.confidence.values())


def test_manual_override_holds_one_coefficient_while_others_learn():
    """An overridden coefficient stays exact and is omitted from RLS updates."""
    true_params = WaterBalanceParams(1.9, 1.2, 0.57, 0.14, 47.0, 17.0)
    override_eta = true_params.eta_irr
    prior = WaterBalanceParams(override_eta, 0.5, 1.1, 0.03, 47.0, 17.0)
    estimator = JointEstimator(
        prior,
        prior_cov=[10.0, 12.0, 2.0, 0.20],
        overrides={
            "eta_irr": override_eta,
            "field_capacity": 47.0,
            "wilting_point": 17.0,
        },
    )

    estimator.fit(_synthetic_observations(true_params, count=240))

    assert estimator.params.eta_irr == pytest.approx(override_eta)
    assert estimator.confidence["eta_irr"] == 1.0
    assert estimator.params.eta_rain == pytest.approx(true_params.eta_rain, abs=0.10)
    assert estimator.params.k_et == pytest.approx(true_params.k_et, abs=0.06)
    assert estimator.params.drain_rate == pytest.approx(true_params.drain_rate, abs=0.04)


def test_confidence_increases_with_more_consistent_data():
    """Posterior covariance maps monotonically to higher confidence."""
    true_params = WaterBalanceParams(1.6, 1.1, 0.65, 0.09, 45.0, 16.0)
    prior = replace(default_params("loam"), field_capacity=45.0, wilting_point=16.0)
    sparse_noisy = JointEstimator(prior, prior_cov=[18.0, 18.0, 2.0, 0.20])
    consistent = JointEstimator(prior, prior_cov=[18.0, 18.0, 2.0, 0.20])
    for estimator in (sparse_noisy, consistent):
        estimator.set_override("field_capacity", 45.0)
        estimator.set_override("wilting_point", 16.0)

    sparse_noisy.fit(
        _synthetic_observations(true_params, count=12, noise_std=0.45)
    )
    consistent.fit(_synthetic_observations(true_params, count=220))

    assert consistent.confidence["eta_irr"] > sparse_noisy.confidence["eta_irr"]
    assert consistent.confidence["eta_rain"] > sparse_noisy.confidence["eta_rain"]


def test_fit_accepts_mapping_observations_and_exposes_expected_confidence_keys():
    """The batch API accepts dict-like intervals for history bootstrap callers."""
    estimator = JointEstimator()
    observation = {
        "theta_start": 40.0,
        "theta_end": 41.0,
        "dt": 1.0,
        "liters": 1.0,
        "rain_mm": 0.0,
        "climate": Climate(20.0, 60.0),
    }

    params = estimator.fit([observation])

    assert isinstance(params, WaterBalanceParams)
    assert set(estimator.confidence) == set(COEFFICIENT_NAMES)
